### ISSUE TITLE
Does not detect docker as being installed on Mac even when it is

### ISSUE THREAD

**Issue by rbreaves** [DarkGhostHunter/Shipyard#6]
So yea.. on version 1.0.4, but also tried 1.0.2 and not getting very far at all. Running MacOS 10.11.6 and oh-my-zsh, but it fails in bash as well.

Running the latest docker version 17.09.0-ce-mac35 (19611) stable channel.

**Comment by DarkGhostHunter** [comment]
I don't have a MacOS, so I can't diagnose.

Can you try `printenv | grep Docker` and `command -v docker` in Terminal? I think these are POSIX and they should work even under cataclysms.

**Comment by DarkGhostHunter** [comment]
Try the new Master. I think I fixed it (i just edited `./.shipyard` script)

**Comment by rbreaves** [comment]
Yea the new master appears to work better. Does not complain about Docker not being installed. It now errors out during the SSL creation step.

![screen shot 2017-10-19 at 1 23 28 pm](https://user-images.githubusercontent.com/10969616/31787249-c23ad1d6-b4d0-11e7-910b-834b32a8cef4.png)

Also just to confirm what happens on what you asked earlier, when I run those commands
printenv | grep Docker returns blank
command -v docker does return '/usr/local/bin/docker'

**Comment by DarkGhostHunter** [comment]
Ty. The first one is done. Pushed a fix to the Cert generation. Pull again `master`.

**Comment by rbreaves** [comment]
Thanks! This appears to have fixed it. I just tried it on another mac I have and will later retry it on my mac desktop as well as that cert issue appears to be the only other issue I had.
