### ISSUE TITLE
Learning more for blog post

### ISSUE THREAD

**Issue by karllhughes** [DarkGhostHunter/Shipyard#7]
Hey DarkGhostHunter,

Apologies for making an issue, but I couldn't find your email address.

My name is Karl and I run a blog that features how-to's and resources for PHP developers who want to learn Docker. Shipyard looks like an awesome tool, so I was hoping maybe I could interview you for the blog to learn more about the project and how it came to be?

I just released my first interview post with Mahmoud Zalt, creator of Laradock, this weekend: https://www.shiphp.com/blog/2017/mahmoud-zalt-laradock

If you're interested, you can email me at khughes.me@gmail.com, and feel free to close this issue when you do.

**Comment by DarkGhostHunter** [comment]
BTW, mailed you.
